
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author aksha
 */
public class JavaPOS extends javax.swing.JFrame {

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnPongal = new javax.swing.JButton();
        jbtnDosa = new javax.swing.JButton();
        jbtnParotta = new javax.swing.JButton();
        jbtnUggani = new javax.swing.JButton();
        jbtnPuri = new javax.swing.JButton();
        jbtnSamosa = new javax.swing.JButton();
        jbtnOmelette = new javax.swing.JButton();
        jbtnIdly = new javax.swing.JButton();
        jbtnAlooSamosa = new javax.swing.JButton();
        jbtnHalfBoil = new javax.swing.JButton();
        jbtnSambarVada = new javax.swing.JButton();
        jbtnTea = new javax.swing.JButton();
        jbtnBreadOmelette = new javax.swing.JButton();
        jbtnUttapam = new javax.swing.JButton();
        jbtnCoffee = new javax.swing.JButton();
        jbtnChapati = new javax.swing.JButton();
        jbtnUpma = new javax.swing.JButton();
        jbtnMeals = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jbtn9 = new javax.swing.JButton();
        jbtn7 = new javax.swing.JButton();
        jbtn8 = new javax.swing.JButton();
        jbtn6 = new javax.swing.JButton();
        jbtn5 = new javax.swing.JButton();
        jbtn4 = new javax.swing.JButton();
        jbtn1 = new javax.swing.JButton();
        jbtn2 = new javax.swing.JButton();
        jbtn3 = new javax.swing.JButton();
        jbtnC = new javax.swing.JButton();
        jbtnDot = new javax.swing.JButton();
        jbtn0 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jPanel31 = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jPanel33 = new javax.swing.JPanel();
        jPanel34 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jPanel36 = new javax.swing.JPanel();
        jPanel37 = new javax.swing.JPanel();
        jPanel38 = new javax.swing.JPanel();
        jPanel39 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        jPanel42 = new javax.swing.JPanel();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        jPanel45 = new javax.swing.JPanel();
        jPanel46 = new javax.swing.JPanel();
        jPanel47 = new javax.swing.JPanel();
        jPanel48 = new javax.swing.JPanel();
        jPanel49 = new javax.swing.JPanel();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jbntExit = new javax.swing.JButton();
        jbtnPay = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jbtnRemove = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jPanel52 = new javax.swing.JPanel();
        jPanel53 = new javax.swing.JPanel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jPanel57 = new javax.swing.JPanel();
        jPanel58 = new javax.swing.JPanel();
        jPanel59 = new javax.swing.JPanel();
        jPanel60 = new javax.swing.JPanel();
        jPanel61 = new javax.swing.JPanel();
        jPanel62 = new javax.swing.JPanel();
        jPanel63 = new javax.swing.JPanel();
        jPanel64 = new javax.swing.JPanel();
        jPanel65 = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jPanel67 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubTotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel68 = new javax.swing.JPanel();
        jPanel69 = new javax.swing.JPanel();
        jPanel70 = new javax.swing.JPanel();
        jPanel71 = new javax.swing.JPanel();
        jPanel72 = new javax.swing.JPanel();
        jPanel73 = new javax.swing.JPanel();
        jPanel74 = new javax.swing.JPanel();
        jPanel75 = new javax.swing.JPanel();
        jPanel76 = new javax.swing.JPanel();
        jPanel77 = new javax.swing.JPanel();
        jPanel78 = new javax.swing.JPanel();
        jPanel79 = new javax.swing.JPanel();
        jPanel80 = new javax.swing.JPanel();
        jPanel81 = new javax.swing.JPanel();
        jPanel82 = new javax.swing.JPanel();
        jPanel83 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtDisplay = new javax.swing.JTextField();
        jtxtChange = new javax.swing.JTextField();
        jcboPayment = new javax.swing.JComboBox<>();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPongal.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPongal.setToolTipText("");
        jbtnPongal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPongalActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPongal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, 120));

        jbtnDosa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDosa.setToolTipText("");
        jbtnDosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDosaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 120, 120));

        jbtnParotta.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnParotta.setToolTipText("");
        jbtnParotta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnParottaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnParotta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 120, 120));

        jbtnUggani.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnUggani.setToolTipText("");
        jbtnUggani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUgganiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUggani, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 120, 120));

        jbtnPuri.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnPuri.setToolTipText("");
        jbtnPuri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPuriActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPuri, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, 120));

        jbtnSamosa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSamosa.setToolTipText("");
        jbtnSamosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSamosaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSamosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 120, 120));

        jbtnOmelette.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnOmelette.setToolTipText("");
        jbtnOmelette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOmeletteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOmelette, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 120, 120));

        jbtnIdly.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnIdly.setToolTipText("");
        jbtnIdly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIdlyActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIdly, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 120, 120));

        jbtnAlooSamosa.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnAlooSamosa.setToolTipText("");
        jbtnAlooSamosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAlooSamosaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAlooSamosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 120, 120));

        jbtnHalfBoil.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnHalfBoil.setToolTipText("");
        jbtnHalfBoil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHalfBoilActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHalfBoil, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 120, 120));

        jbtnSambarVada.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnSambarVada.setToolTipText("");
        jbtnSambarVada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSambarVadaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSambarVada, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 120, 120));

        jbtnTea.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnTea.setToolTipText("");
        jbtnTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTeaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 120, 120));

        jbtnBreadOmelette.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnBreadOmelette.setToolTipText("");
        jbtnBreadOmelette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBreadOmeletteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBreadOmelette, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 120, 120));

        jbtnUttapam.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnUttapam.setToolTipText("");
        jbtnUttapam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUttapamActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUttapam, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 120, 120));

        jbtnCoffee.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnCoffee.setToolTipText("");
        jbtnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCoffeeActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 120, 120));

        jbtnChapati.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnChapati.setToolTipText("");
        jbtnChapati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnChapatiActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnChapati, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, 120, 120));

        jbtnUpma.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnUpma.setToolTipText("");
        jbtnUpma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpmaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnUpma, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 120, 120));

        jbtnMeals.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnMeals.setToolTipText("");
        jbtnMeals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMealsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMeals, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 120, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 790, 410));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtn9.setBackground(new java.awt.Color(204, 204, 204));
        jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setToolTipText("");
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 70, 90));

        jbtn7.setBackground(new java.awt.Color(204, 204, 204));
        jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setToolTipText("");
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 90));

        jbtn8.setBackground(new java.awt.Color(204, 204, 204));
        jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setToolTipText("");
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 70, 90));

        jbtn6.setBackground(new java.awt.Color(204, 204, 204));
        jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setToolTipText("");
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 70, 90));

        jbtn5.setBackground(new java.awt.Color(204, 204, 204));
        jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setToolTipText("");
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 70, 90));

        jbtn4.setBackground(new java.awt.Color(204, 204, 204));
        jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setToolTipText("");
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 90));

        jbtn1.setBackground(new java.awt.Color(204, 204, 204));
        jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setToolTipText("");
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 70, 90));

        jbtn2.setBackground(new java.awt.Color(204, 204, 204));
        jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setToolTipText("");
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 70, 90));

        jbtn3.setBackground(new java.awt.Color(204, 204, 204));
        jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setToolTipText("");
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 70, 90));

        jbtnC.setBackground(new java.awt.Color(204, 204, 204));
        jbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnC.setText("C");
        jbtnC.setToolTipText("");
        jbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 70, 90));

        jbtnDot.setBackground(new java.awt.Color(204, 204, 204));
        jbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnDot.setText(".");
        jbtnDot.setToolTipText("");
        jbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 70, 90));

        jbtn0.setBackground(new java.awt.Color(204, 204, 204));
        jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setToolTipText("");
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 70, 90));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 410));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Item");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Qty");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 300, 340));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jPanel20.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel20.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel23.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel23.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel22.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel20.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel24.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel25.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel24.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel26.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel27.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel27.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel26.add(jPanel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel24.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel28.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel28.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel29.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel29.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel28.add(jPanel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel30.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel30.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel31.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel31.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel30.add(jPanel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel28.add(jPanel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel32.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel32.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel33.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel33.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel32.add(jPanel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel34.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel34.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel35.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel35.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel34.add(jPanel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel32.add(jPanel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel28.add(jPanel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel24.add(jPanel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel20.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel36.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel36.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel37.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel37.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel36.add(jPanel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel38.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel38.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel39.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel39.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel38.add(jPanel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel36.add(jPanel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel40.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel40.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel41.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel41.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel40.add(jPanel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel42.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel42.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel43.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel43.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel42.add(jPanel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel40.add(jPanel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel44.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel44.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel45.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel45.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel44.add(jPanel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel46.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel46.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel47.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel47.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel46.add(jPanel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel44.add(jPanel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel48.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel48.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel49.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel49.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel48.add(jPanel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel50.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel50.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel51.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel51.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel50.add(jPanel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel48.add(jPanel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel44.add(jPanel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel40.add(jPanel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel36.add(jPanel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jbntExit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbntExit.setText("Exit");
        jbntExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbntExitActionPerformed(evt);
            }
        });
        jPanel36.add(jbntExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 370, 40));

        jbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPay.setText("Pay");
        jbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPayActionPerformed(evt);
            }
        });
        jPanel36.add(jbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 160, 40));

        jbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnPrint.setText("Print");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel36.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 160, 40));

        jbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnRemove.setText("Remove");
        jbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRemoveActionPerformed(evt);
            }
        });
        jPanel36.add(jbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, 160, 40));

        jbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel36.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 160, 40));

        jPanel20.add(jPanel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 20, 410, 160));

        jPanel52.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel52.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel53.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel53.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel52.add(jPanel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel54.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel54.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel55.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel55.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel54.add(jPanel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel52.add(jPanel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel56.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel56.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel57.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel57.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel56.add(jPanel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel58.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel58.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel59.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel59.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel58.add(jPanel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel56.add(jPanel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel60.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel60.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel61.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel61.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel60.add(jPanel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel62.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel62.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel63.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel63.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel62.add(jPanel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel60.add(jPanel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel64.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel64.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel65.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel65.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel64.add(jPanel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel66.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel66.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel67.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel67.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel66.add(jPanel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel64.add(jPanel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel60.add(jPanel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel56.add(jPanel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel52.add(jPanel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel52.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("SubTotal");
        jPanel52.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Tax");
        jPanel52.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTotal.setToolTipText("");
        jtxtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTotalActionPerformed(evt);
            }
        });
        jPanel52.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 160, -1));

        jtxtSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtSubTotal.setToolTipText("");
        jtxtSubTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtSubTotalActionPerformed(evt);
            }
        });
        jPanel52.add(jtxtSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 160, -1));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTax.setToolTipText("");
        jPanel52.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 160, -1));

        jPanel20.add(jPanel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 160));

        jPanel68.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel68.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel69.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel69.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel68.add(jPanel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel70.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel70.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel71.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel71.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel70.add(jPanel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel68.add(jPanel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel72.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel72.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel73.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel73.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel72.add(jPanel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel74.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel74.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel75.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel75.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel74.add(jPanel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel72.add(jPanel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel76.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel76.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel77.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel77.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel76.add(jPanel77, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel78.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel78.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel79.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel79.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel78.add(jPanel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel76.add(jPanel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel80.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel80.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel81.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel81.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel80.add(jPanel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel82.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel82.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel83.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel83.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel82.add(jPanel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 1360, 120));

        jPanel80.add(jPanel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 120));

        jPanel76.add(jPanel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel72.add(jPanel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jPanel68.add(jPanel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 1360, 120));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Change");
        jPanel68.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Cash");
        jPanel68.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Payment Method");
        jPanel68.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtDisplay.setToolTipText("");
        jtxtDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDisplayActionPerformed(evt);
            }
        });
        jPanel68.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 140, -1));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtChange.setToolTipText("");
        jtxtChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtChangeActionPerformed(evt);
            }
        });
        jPanel68.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 140, -1));

        jcboPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jcboPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcboPaymentActionPerformed(evt);
            }
        });
        jPanel68.add(jcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 140, -1));

        jPanel20.add(jPanel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 410, 160));

        getContentPane().add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 1360, 190));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DlTt", 0, 36)); // NOI18N
        jtxtBarCode.setToolTipText("");
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 300, 70));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//==============================Function calculate=================================================
    
    public void ItemCost()
    {
        double sum = 0;
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        jtxtSubTotal.setText(Double.toString(sum));
        double cTotal1 = Double.parseDouble(jtxtSubTotal.getText());
        
        double cTax = (cTotal1 * 3.9)/100;
        String iTaxTotal = String.format("₹ %.2f", cTax);
        jtxtTax.setText(iTaxTotal);
        
        String iSubTotal = String.format("₹ %.2f", cTotal1);
        jtxtSubTotal.setText(iSubTotal);
        
        String iTotal = String.format("₹ %.2f", cTotal1 + cTax);
        jtxtTotal.setText(iTotal);
        
        String BarCode = String.format("Total is %.2f", cTotal1 + cTax);
        jtxtBarCode.setText(BarCode);
        
    }
    
    //==============================Function Change=============================================
    
    public void Change()
    {
        double sum = 0;
        double tax = 3.9;
        double cash = Double.parseDouble(jtxtDisplay.getText());
        
        for(int i = 0; i < jTable1.getRowCount(); i++)
        {
            sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        
        double cTax = (sum * 3.9)/100;
        double cChange = (cash - (sum + cTax));
        
        String ChangeGiven = String.format("₹ %.2f", cChange);
        jtxtChange.setText(ChangeGiven);
    }
    
    
    private void jtxtSubTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtSubTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtSubTotalActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn9.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtnDosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDosaActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Dosa", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnDosaActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn8.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn4.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn5.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn6.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn1.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn2.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn3.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText()+jbtn0.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
    }//GEN-LAST:event_jbtnCActionPerformed

    private void jbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDotActionPerformed
        
        if(! jtxtDisplay.getText().contains("."))
        {
            jtxtDisplay.setText(jtxtDisplay.getText()+jbtnDot.getText());
        }
    }//GEN-LAST:event_jbtnDotActionPerformed

    private void jbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPayActionPerformed
        if(jcboPayment.getSelectedItem().equals("Cash"))
            {
                Change();
            }
            else
            {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
            }
    }//GEN-LAST:event_jbtnPayActionPerformed

    private void jtxtChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtChangeActionPerformed

    private void jtxtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTotalActionPerformed

    private void jbtnPuriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPuriActionPerformed
        double PriceOfItem = 20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Puri", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnPuriActionPerformed

    private void jbtnIdlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIdlyActionPerformed
        double PriceOfItem = 40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Idly", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnIdlyActionPerformed

    private void jbtnSambarVadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSambarVadaActionPerformed
        double PriceOfItem = 20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sambar Vada", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSambarVadaActionPerformed

    private void jbtnUttapamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUttapamActionPerformed
        double PriceOfItem = 25;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Uttapam", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnUttapamActionPerformed

    private void jbtnUpmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpmaActionPerformed
        double PriceOfItem = 20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Upma", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnUpmaActionPerformed

    private void jbtnPongalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPongalActionPerformed
        double PriceOfItem = 20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pongal", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnPongalActionPerformed

    private void jbtnUgganiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUgganiActionPerformed
        double PriceOfItem = 15;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Uggani", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnUgganiActionPerformed

    private void jbtnOmeletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOmeletteActionPerformed
        double PriceOfItem = 15;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Omelette", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnOmeletteActionPerformed

    private void jbtnHalfBoilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHalfBoilActionPerformed
        double PriceOfItem = 10;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Half-Boiled Egg", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnHalfBoilActionPerformed

    private void jbtnBreadOmeletteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBreadOmeletteActionPerformed
        double PriceOfItem = 25;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Bread Omelette", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnBreadOmeletteActionPerformed

    private void jbtnChapatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnChapatiActionPerformed
        double PriceOfItem = 25;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Chapati", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnChapatiActionPerformed

    private void jbtnParottaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnParottaActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Parotta", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnParottaActionPerformed

    private void jbtnSamosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSamosaActionPerformed
        double PriceOfItem = 20;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Samosa", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnSamosaActionPerformed

    private void jbtnAlooSamosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAlooSamosaActionPerformed
        double PriceOfItem = 30;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Aloo Samosa", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnAlooSamosaActionPerformed

    private void jbtnTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTeaActionPerformed
        double PriceOfItem = 10;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Tea", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnTeaActionPerformed

    private void jbtnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCoffeeActionPerformed
        double PriceOfItem = 10;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coffee", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnCoffeeActionPerformed

    private void jbtnMealsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMealsActionPerformed
        double PriceOfItem = 60;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Meals", "1", PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnMealsActionPerformed

    private void jcboPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcboPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcboPaymentActionPerformed

    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubTotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        MessageFormat header = new MessageFormat("Printing in Process");
        MessageFormat footer = new MessageFormat("Page {0, number, integer}");
        
        try
        {
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch(java.awt.print.PrinterException e)
                {
                    System.err.format("No Printer found", e.getMessage());
                }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRemoveActionPerformed
         DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         
         int RemoveItem = jTable1.getSelectedRow();
         if(RemoveItem >= 0)
         {
             model.removeRow(RemoveItem);
         }
         
         ItemCost();
         
         if(jcboPayment.getSelectedItem().equals("cash"))
            {
                Change();
            }
            else
            {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
            }
         
    }//GEN-LAST:event_jbtnRemoveActionPerformed
private JFrame frame;
    private void jbntExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbntExitActionPerformed
        
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Point of Sale",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jbntExitActionPerformed

    private void jtxtDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDisplayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel38;
    private javax.swing.JPanel jPanel39;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JPanel jPanel45;
    private javax.swing.JPanel jPanel46;
    private javax.swing.JPanel jPanel47;
    private javax.swing.JPanel jPanel48;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel jPanel57;
    private javax.swing.JPanel jPanel58;
    private javax.swing.JPanel jPanel59;
    private javax.swing.JPanel jPanel60;
    private javax.swing.JPanel jPanel61;
    private javax.swing.JPanel jPanel62;
    private javax.swing.JPanel jPanel63;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel65;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel69;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JPanel jPanel72;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JPanel jPanel77;
    private javax.swing.JPanel jPanel78;
    private javax.swing.JPanel jPanel79;
    private javax.swing.JPanel jPanel80;
    private javax.swing.JPanel jPanel81;
    private javax.swing.JPanel jPanel82;
    private javax.swing.JPanel jPanel83;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbntExit;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnAlooSamosa;
    private javax.swing.JButton jbtnBreadOmelette;
    private javax.swing.JButton jbtnC;
    private javax.swing.JButton jbtnChapati;
    private javax.swing.JButton jbtnCoffee;
    private javax.swing.JButton jbtnDosa;
    private javax.swing.JButton jbtnDot;
    private javax.swing.JButton jbtnHalfBoil;
    private javax.swing.JButton jbtnIdly;
    private javax.swing.JButton jbtnMeals;
    private javax.swing.JButton jbtnOmelette;
    private javax.swing.JButton jbtnParotta;
    private javax.swing.JButton jbtnPay;
    private javax.swing.JButton jbtnPongal;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnPuri;
    private javax.swing.JButton jbtnRemove;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnSambarVada;
    private javax.swing.JButton jbtnSamosa;
    private javax.swing.JButton jbtnTea;
    private javax.swing.JButton jbtnUggani;
    private javax.swing.JButton jbtnUpma;
    private javax.swing.JButton jbtnUttapam;
    private javax.swing.JComboBox<String> jcboPayment;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubTotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
